server:
  port: 8080
  servlet:
    context-path: /CTB

spring:
  application:
    name: ctbsb
#  profiles:
#    active: dev
  mail:
    host: smtp.163.com
    username: ctbofficial@163.com  #发送方的邮箱
    password: CMIGMQMFSDGIKTSF
    defaultEncoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 20000
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:mysql://localhost:3306/ctb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

file-save-path: C:\Users\Evergarden\Desktop\CTB\CTBSB\ctbsb\src\main\resources\static

#logging:
#  level:
#    root: info
#    com.xiaozhuo.ctbsb: debug

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  SECRET: ctb-secret
  EXPIRATION_TIME: 432000000 #

#jwt:
#  tokenHeader: Authorization #JWT存储的请求头
#  SECRET: ctb-secret #JWT加解密使用的密钥
#  EXPIRATION_TIME: 604800 #JWT的超期限时间(60*60*24*7)
#  tokenHead: 'Bearer '  #JWT负载中拿到开头

#redis:
#  database: ctb
#  key:
#    admin: 'ums:admin'
#    resourceList: 'ums:resourceList'
#  expire:
#    common: 86400 # 24小时

#secure:
#  ignored:
#    urls: #安全路径白名单
#      - /swagger-ui.html
#      - /swagger-resources/**
#      - /swagger/**
#      - /**/v2/api-docs
#      - /**/*.js
#      - /**/*.css
#      - /**/*.png
#      - /**/*.ico
#      - /webjars/springfox-swagger-ui/**
#      - /actuator/**
#      - /druid/**
#      - /admin/login
#      - /admin/register
#      - /admin/info
#      - /admin/logout
