spring:
  profiles: prod
  mail:
    host: smtp.163.com
    username: ctbofficial@163.com  #发送方的邮箱
    password: CMIGMQMFSDGIKTSF
    defaultEncoding: utf-8
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            socketFactory:
              fallback: false
              class: javax.net.ssl.SSLSocketFactory
          auth: true
          timeout: 20000
          starttls:
            enable: true
            required: true
    protocol: smtp
  datasource:
    url: jdbc:mysql://106.14.25.22:3306/ctb?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 106.14.25.22 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: #ctbsb1045130102 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  data:
    elasticsearch:
      cluster-name: ctb
      cluster-nodes: 106.14.25.22:9300

file-save-path: /mnt #C:\Users\Evergarden\Desktop\CTB\CTBSB\ctbsb\src\main\resources\static #E:\CTB\file #todo

#logging:
#  level:
#    root: info
#    com.xiaozhuo.ctbsb: debug

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  SECRET: ctb-secret
  EXPIRATION_TIME: 3600000 #过期时间1hour


freemarker:
  cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
  suffix: .html # 模版后缀名 默认为ftl
  charset: UTF-8 # 文件编码
  template-loader-path: classpath:/templates/  # 存放模板的文件夹，以resource文件夹为相对路径

#jwt:
#  tokenHeader: Authorization #JWT存储的请求头
#  SECRET: ctb-secret #JWT加解密使用的密钥
#  EXPIRATION_TIME: 604800 #JWT的超期限时间(60*60*24*7)
#  tokenHead: 'Bearer '  #JWT负载中拿到开头

#redis:
#  database: ctb
#  key:
#    admin: 'ums:admin'
#    resourceList: 'ums:resourceList'
#  expire:
#    common: 86400 # 24小时

#secure:
#  ignored:
#    urls: #安全路径白名单
#      - /swagger-ui.html
#      - /swagger-resources/**
#      - /swagger/**
#      - /**/v2/api-docs
#      - /**/*.js
#      - /**/*.css
#      - /**/*.png
#      - /**/*.ico
#      - /webjars/springfox-swagger-ui/**
#      - /actuator/**
#      - /druid/**
#      - /admin/login
#      - /admin/register
#      - /admin/info
#      - /admin/logout
